"""Add Phase 2 meetings and documents tables

Revision ID: 01e4e7c97aed
Revises: 96333ed41609
Create Date: 2025-09-08 17:03:16.968845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e4e7c97aed'
down_revision: Union[str, None] = '96333ed41609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee_meetings',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('committee_id', sa.UUID(), nullable=False),
    sa.Column('session_key', sa.String(length=20), nullable=False),
    sa.Column('committee_code', sa.String(length=20), nullable=False),
    sa.Column('meeting_guid', sa.String(length=100), nullable=False),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('alternate_location', sa.String(length=500), nullable=True),
    sa.Column('posted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meeting_status_code', sa.String(length=10), nullable=True),
    sa.Column('meeting_status', sa.String(length=50), nullable=True),
    sa.Column('agenda_url', sa.String(length=1000), nullable=True),
    sa.Column('agenda_revision_number', sa.Integer(), nullable=True),
    sa.Column('olis_created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('olis_modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['legislative_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_guid')
    )
    op.create_index('idx_meeting_committee', 'committee_meetings', ['committee_code'], unique=False)
    op.create_index('idx_meeting_date', 'committee_meetings', ['meeting_date'], unique=False)
    op.create_index('idx_meeting_session', 'committee_meetings', ['session_key'], unique=False)
    op.create_index('idx_meeting_status', 'committee_meetings', ['meeting_status_code'], unique=False)
    op.create_table('committee_agenda_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('committee_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('measure_id', sa.UUID(), nullable=True),
    sa.Column('committee_agenda_item_id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.String(length=20), nullable=False),
    sa.Column('committee_code', sa.String(length=20), nullable=False),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('measure_prefix', sa.String(length=10), nullable=True),
    sa.Column('measure_number', sa.Integer(), nullable=True),
    sa.Column('meeting_type', sa.String(length=100), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('print_order', sa.String(length=20), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('board_name', sa.String(length=200), nullable=True),
    sa.Column('executive_appointee', sa.String(length=200), nullable=True),
    sa.Column('olis_created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('olis_modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['measure_id'], ['measures.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['committee_meetings.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['legislative_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('committee_agenda_item_id')
    )
    op.create_index('idx_agenda_item_committee', 'committee_agenda_items', ['committee_code'], unique=False)
    op.create_index('idx_agenda_item_date', 'committee_agenda_items', ['meeting_date'], unique=False)
    op.create_index('idx_agenda_item_measure', 'committee_agenda_items', ['measure_prefix', 'measure_number'], unique=False)
    op.create_index('idx_agenda_item_session', 'committee_agenda_items', ['session_key'], unique=False)
    op.create_table('committee_meeting_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('committee_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('measure_id', sa.UUID(), nullable=True),
    sa.Column('committee_meeting_document_id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.String(length=20), nullable=False),
    sa.Column('committee_code', sa.String(length=20), nullable=False),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exhibit_reference', sa.String(length=50), nullable=True),
    sa.Column('exhibit_title', sa.String(length=500), nullable=False),
    sa.Column('submitter', sa.String(length=200), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_url', sa.String(length=1000), nullable=False),
    sa.Column('measure_prefix', sa.String(length=10), nullable=True),
    sa.Column('measure_number', sa.Integer(), nullable=True),
    sa.Column('olis_created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('olis_modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['measure_id'], ['measures.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['committee_meetings.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['legislative_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('committee_meeting_document_id')
    )
    op.create_index('idx_meeting_doc_committee', 'committee_meeting_documents', ['committee_code'], unique=False)
    op.create_index('idx_meeting_doc_date', 'committee_meeting_documents', ['meeting_date'], unique=False)
    op.create_index('idx_meeting_doc_measure', 'committee_meeting_documents', ['measure_prefix', 'measure_number'], unique=False)
    op.create_index('idx_meeting_doc_session', 'committee_meeting_documents', ['session_key'], unique=False)
    op.create_index('idx_meeting_doc_type', 'committee_meeting_documents', ['document_type'], unique=False)
    op.create_table('measure_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('measure_id', sa.UUID(), nullable=False),
    sa.Column('session_key', sa.String(length=20), nullable=False),
    sa.Column('measure_prefix', sa.String(length=10), nullable=False),
    sa.Column('measure_number', sa.Integer(), nullable=False),
    sa.Column('version_description', sa.String(length=100), nullable=False),
    sa.Column('document_url', sa.String(length=1000), nullable=False),
    sa.Column('olis_created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('olis_modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['measure_id'], ['measures.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['legislative_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_key', 'measure_prefix', 'measure_number', 'version_description', name='uq_measure_document')
    )
    op.create_index('idx_measure_doc_measure', 'measure_documents', ['measure_prefix', 'measure_number'], unique=False)
    op.create_index('idx_measure_doc_session', 'measure_documents', ['session_key'], unique=False)
    op.create_index('idx_measure_doc_version', 'measure_documents', ['version_description'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_measure_doc_version', table_name='measure_documents')
    op.drop_index('idx_measure_doc_session', table_name='measure_documents')
    op.drop_index('idx_measure_doc_measure', table_name='measure_documents')
    op.drop_table('measure_documents')
    op.drop_index('idx_meeting_doc_type', table_name='committee_meeting_documents')
    op.drop_index('idx_meeting_doc_session', table_name='committee_meeting_documents')
    op.drop_index('idx_meeting_doc_measure', table_name='committee_meeting_documents')
    op.drop_index('idx_meeting_doc_date', table_name='committee_meeting_documents')
    op.drop_index('idx_meeting_doc_committee', table_name='committee_meeting_documents')
    op.drop_table('committee_meeting_documents')
    op.drop_index('idx_agenda_item_session', table_name='committee_agenda_items')
    op.drop_index('idx_agenda_item_measure', table_name='committee_agenda_items')
    op.drop_index('idx_agenda_item_date', table_name='committee_agenda_items')
    op.drop_index('idx_agenda_item_committee', table_name='committee_agenda_items')
    op.drop_table('committee_agenda_items')
    op.drop_index('idx_meeting_status', table_name='committee_meetings')
    op.drop_index('idx_meeting_session', table_name='committee_meetings')
    op.drop_index('idx_meeting_date', table_name='committee_meetings')
    op.drop_index('idx_meeting_committee', table_name='committee_meetings')
    op.drop_table('committee_meetings')
    # ### end Alembic commands ###