"""Add FloorSessionAgendaItem model

Revision ID: 4cadb642c152
Revises: 59d3c682e79c
Create Date: 2025-09-08 18:38:52.484668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cadb642c152'
down_revision: Union[str, None] = '59d3c682e79c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floor_session_agenda_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('measure_id', sa.UUID(), nullable=True),
    sa.Column('agenda_id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.String(length=20), nullable=False),
    sa.Column('measure_prefix', sa.String(length=10), nullable=False),
    sa.Column('measure_number', sa.Integer(), nullable=False),
    sa.Column('schedule_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('chamber', sa.String(length=10), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('order_of_business', sa.String(length=200), nullable=False),
    sa.Column('carrier_code', sa.String(length=100), nullable=True),
    sa.Column('olis_created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('olis_modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['measure_id'], ['measures.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['legislative_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agenda_id')
    )
    op.create_index('idx_floor_agenda_chamber', 'floor_session_agenda_items', ['chamber'], unique=False)
    op.create_index('idx_floor_agenda_completed', 'floor_session_agenda_items', ['completed'], unique=False)
    op.create_index('idx_floor_agenda_date', 'floor_session_agenda_items', ['schedule_date'], unique=False)
    op.create_index('idx_floor_agenda_measure', 'floor_session_agenda_items', ['measure_prefix', 'measure_number'], unique=False)
    op.create_index('idx_floor_agenda_order', 'floor_session_agenda_items', ['order_of_business'], unique=False)
    op.create_index('idx_floor_agenda_session', 'floor_session_agenda_items', ['session_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_floor_agenda_session', table_name='floor_session_agenda_items')
    op.drop_index('idx_floor_agenda_order', table_name='floor_session_agenda_items')
    op.drop_index('idx_floor_agenda_measure', table_name='floor_session_agenda_items')
    op.drop_index('idx_floor_agenda_date', table_name='floor_session_agenda_items')
    op.drop_index('idx_floor_agenda_completed', table_name='floor_session_agenda_items')
    op.drop_index('idx_floor_agenda_chamber', table_name='floor_session_agenda_items')
    op.drop_table('floor_session_agenda_items')
    # ### end Alembic commands ###