"""Add Phase 1 legislators and voting tables

Revision ID: 96333ed41609
Revises: 2696d4651dbe
Create Date: 2025-09-08 16:46:20.410832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96333ed41609'
down_revision: Union[str, None] = '2696d4651dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legislators',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('session_key', sa.String(length=20), nullable=False),
    sa.Column('legislator_code', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('chamber', sa.String(length=10), nullable=False),
    sa.Column('party', sa.String(length=50), nullable=True),
    sa.Column('district_number', sa.String(length=10), nullable=True),
    sa.Column('capitol_address', sa.Text(), nullable=True),
    sa.Column('capitol_phone', sa.String(length=50), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('olis_created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('olis_modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['legislative_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_key', 'legislator_code', name='uq_legislator_session_code')
    )
    op.create_index('idx_legislator_chamber', 'legislators', ['chamber'], unique=False)
    op.create_index('idx_legislator_party', 'legislators', ['party'], unique=False)
    op.create_index('idx_legislator_session_key', 'legislators', ['session_key'], unique=False)
    op.create_table('committee_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('committee_id', sa.UUID(), nullable=False),
    sa.Column('legislator_id', sa.UUID(), nullable=False),
    sa.Column('session_key', sa.String(length=20), nullable=False),
    sa.Column('committee_code', sa.String(length=20), nullable=False),
    sa.Column('legislator_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('olis_created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('olis_modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['legislator_id'], ['legislators.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['legislative_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_key', 'committee_code', 'legislator_code', name='uq_committee_member')
    )
    op.create_index('idx_committee_member_committee', 'committee_members', ['committee_code'], unique=False)
    op.create_index('idx_committee_member_legislator', 'committee_members', ['legislator_code'], unique=False)
    op.create_index('idx_committee_member_session', 'committee_members', ['session_key'], unique=False)
    op.create_table('committee_votes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('committee_id', sa.UUID(), nullable=False),
    sa.Column('measure_id', sa.UUID(), nullable=False),
    sa.Column('legislator_id', sa.UUID(), nullable=False),
    sa.Column('committee_vote_id', sa.Integer(), nullable=False),
    sa.Column('committee_report_id', sa.Integer(), nullable=True),
    sa.Column('committee_agenda_item_id', sa.Integer(), nullable=True),
    sa.Column('session_key', sa.String(length=20), nullable=False),
    sa.Column('committee_code', sa.String(length=20), nullable=False),
    sa.Column('measure_prefix', sa.String(length=10), nullable=False),
    sa.Column('measure_number', sa.Integer(), nullable=False),
    sa.Column('vote_name', sa.String(length=200), nullable=False),
    sa.Column('meaning', sa.String(length=50), nullable=False),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('olis_created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('olis_modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['legislator_id'], ['legislators.id'], ),
    sa.ForeignKeyConstraint(['measure_id'], ['measures.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['legislative_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('committee_vote_id')
    )
    op.create_index('idx_committee_vote_committee', 'committee_votes', ['committee_code'], unique=False)
    op.create_index('idx_committee_vote_date', 'committee_votes', ['meeting_date'], unique=False)
    op.create_index('idx_committee_vote_legislator', 'committee_votes', ['vote_name'], unique=False)
    op.create_index('idx_committee_vote_measure', 'committee_votes', ['measure_prefix', 'measure_number'], unique=False)
    op.create_index('idx_committee_vote_result', 'committee_votes', ['meaning'], unique=False)
    op.create_index('idx_committee_vote_session', 'committee_votes', ['session_key'], unique=False)
    op.create_table('measure_history_actions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('measure_id', sa.UUID(), nullable=False),
    sa.Column('measure_history_id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.String(length=20), nullable=False),
    sa.Column('measure_prefix', sa.String(length=10), nullable=False),
    sa.Column('measure_number', sa.Integer(), nullable=False),
    sa.Column('chamber', sa.String(length=10), nullable=True),
    sa.Column('action_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('vote_text', sa.Text(), nullable=True),
    sa.Column('public_notification', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('olis_created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('olis_modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['measure_id'], ['measures.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['legislative_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measure_history_id')
    )
    op.create_index('idx_history_action_chamber', 'measure_history_actions', ['chamber'], unique=False)
    op.create_index('idx_history_action_date', 'measure_history_actions', ['action_date'], unique=False)
    op.create_index('idx_history_action_measure', 'measure_history_actions', ['measure_prefix', 'measure_number'], unique=False)
    op.create_index('idx_history_action_session', 'measure_history_actions', ['session_key'], unique=False)
    op.create_table('measure_votes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('measure_id', sa.UUID(), nullable=False),
    sa.Column('legislator_id', sa.UUID(), nullable=False),
    sa.Column('measure_vote_id', sa.Integer(), nullable=False),
    sa.Column('measure_history_id', sa.Integer(), nullable=True),
    sa.Column('session_key', sa.String(length=20), nullable=False),
    sa.Column('measure_prefix', sa.String(length=10), nullable=False),
    sa.Column('measure_number', sa.Integer(), nullable=False),
    sa.Column('vote', sa.String(length=50), nullable=False),
    sa.Column('vote_name', sa.String(length=200), nullable=False),
    sa.Column('chamber', sa.String(length=10), nullable=False),
    sa.Column('action_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('olis_created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('olis_modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['legislator_id'], ['legislators.id'], ),
    sa.ForeignKeyConstraint(['measure_id'], ['measures.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['legislative_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measure_vote_id')
    )
    op.create_index('idx_measure_vote_chamber', 'measure_votes', ['chamber'], unique=False)
    op.create_index('idx_measure_vote_date', 'measure_votes', ['action_date'], unique=False)
    op.create_index('idx_measure_vote_legislator', 'measure_votes', ['vote_name'], unique=False)
    op.create_index('idx_measure_vote_measure', 'measure_votes', ['measure_prefix', 'measure_number'], unique=False)
    op.create_index('idx_measure_vote_result', 'measure_votes', ['vote'], unique=False)
    op.create_index('idx_measure_vote_session', 'measure_votes', ['session_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_measure_vote_session', table_name='measure_votes')
    op.drop_index('idx_measure_vote_result', table_name='measure_votes')
    op.drop_index('idx_measure_vote_measure', table_name='measure_votes')
    op.drop_index('idx_measure_vote_legislator', table_name='measure_votes')
    op.drop_index('idx_measure_vote_date', table_name='measure_votes')
    op.drop_index('idx_measure_vote_chamber', table_name='measure_votes')
    op.drop_table('measure_votes')
    op.drop_index('idx_history_action_session', table_name='measure_history_actions')
    op.drop_index('idx_history_action_measure', table_name='measure_history_actions')
    op.drop_index('idx_history_action_date', table_name='measure_history_actions')
    op.drop_index('idx_history_action_chamber', table_name='measure_history_actions')
    op.drop_table('measure_history_actions')
    op.drop_index('idx_committee_vote_session', table_name='committee_votes')
    op.drop_index('idx_committee_vote_result', table_name='committee_votes')
    op.drop_index('idx_committee_vote_measure', table_name='committee_votes')
    op.drop_index('idx_committee_vote_legislator', table_name='committee_votes')
    op.drop_index('idx_committee_vote_date', table_name='committee_votes')
    op.drop_index('idx_committee_vote_committee', table_name='committee_votes')
    op.drop_table('committee_votes')
    op.drop_index('idx_committee_member_session', table_name='committee_members')
    op.drop_index('idx_committee_member_legislator', table_name='committee_members')
    op.drop_index('idx_committee_member_committee', table_name='committee_members')
    op.drop_table('committee_members')
    op.drop_index('idx_legislator_session_key', table_name='legislators')
    op.drop_index('idx_legislator_party', table_name='legislators')
    op.drop_index('idx_legislator_chamber', table_name='legislators')
    op.drop_table('legislators')
    # ### end Alembic commands ###