"""add_floor_letter_model

Revision ID: 972a295fa91f
Revises: 4cadb642c152
Create Date: 2025-09-08 18:49:14.366511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972a295fa91f'
down_revision: Union[str, None] = '4cadb642c152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floor_letters',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('measure_id', sa.UUID(), nullable=True),
    sa.Column('floor_letter_id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.String(length=20), nullable=False),
    sa.Column('measure_prefix', sa.String(length=10), nullable=True),
    sa.Column('measure_number', sa.Integer(), nullable=True),
    sa.Column('letter_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chamber', sa.String(length=10), nullable=False),
    sa.Column('letter_description', sa.String(length=500), nullable=False),
    sa.Column('letter_title', sa.String(length=500), nullable=False),
    sa.Column('floor_letter_url', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['measure_id'], ['measures.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['legislative_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor_letter_id')
    )
    op.create_index('idx_floor_letter_chamber', 'floor_letters', ['chamber'], unique=False)
    op.create_index('idx_floor_letter_date', 'floor_letters', ['letter_date'], unique=False)
    op.create_index('idx_floor_letter_measure', 'floor_letters', ['measure_prefix', 'measure_number'], unique=False)
    op.create_index('idx_floor_letter_session', 'floor_letters', ['session_key'], unique=False)
    op.create_index('idx_floor_letter_title', 'floor_letters', ['letter_title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_floor_letter_title', table_name='floor_letters')
    op.drop_index('idx_floor_letter_session', table_name='floor_letters')
    op.drop_index('idx_floor_letter_measure', table_name='floor_letters')
    op.drop_index('idx_floor_letter_date', table_name='floor_letters')
    op.drop_index('idx_floor_letter_chamber', table_name='floor_letters')
    op.drop_table('floor_letters')
    # ### end Alembic commands ###