"""Add CommitteeProposedAmendment model

Revision ID: 59d3c682e79c
Revises: 26670c52c436
Create Date: 2025-09-08 18:27:49.991572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d3c682e79c'
down_revision: Union[str, None] = '26670c52c436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee_proposed_amendments',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('committee_id', sa.UUID(), nullable=False),
    sa.Column('measure_id', sa.UUID(), nullable=True),
    sa.Column('agenda_item_id', sa.UUID(), nullable=True),
    sa.Column('proposed_amendment_id', sa.Integer(), nullable=False),
    sa.Column('committee_agenda_item_id', sa.Integer(), nullable=True),
    sa.Column('session_key', sa.String(length=20), nullable=False),
    sa.Column('committee_code', sa.String(length=20), nullable=False),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('measure_prefix', sa.String(length=10), nullable=False),
    sa.Column('measure_number', sa.Integer(), nullable=False),
    sa.Column('amendment_number', sa.String(length=50), nullable=False),
    sa.Column('meaning', sa.String(length=50), nullable=False),
    sa.Column('proposed_amendment_url', sa.String(length=1000), nullable=False),
    sa.Column('olis_created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('olis_modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agenda_item_id'], ['committee_agenda_items.id'], ),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['measure_id'], ['measures.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['legislative_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposed_amendment_id')
    )
    op.create_index('idx_proposed_amendment_committee', 'committee_proposed_amendments', ['committee_code'], unique=False)
    op.create_index('idx_proposed_amendment_date', 'committee_proposed_amendments', ['meeting_date'], unique=False)
    op.create_index('idx_proposed_amendment_meaning', 'committee_proposed_amendments', ['meaning'], unique=False)
    op.create_index('idx_proposed_amendment_measure', 'committee_proposed_amendments', ['measure_prefix', 'measure_number'], unique=False)
    op.create_index('idx_proposed_amendment_session', 'committee_proposed_amendments', ['session_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_proposed_amendment_session', table_name='committee_proposed_amendments')
    op.drop_index('idx_proposed_amendment_measure', table_name='committee_proposed_amendments')
    op.drop_index('idx_proposed_amendment_meaning', table_name='committee_proposed_amendments')
    op.drop_index('idx_proposed_amendment_date', table_name='committee_proposed_amendments')
    op.drop_index('idx_proposed_amendment_committee', table_name='committee_proposed_amendments')
    op.drop_table('committee_proposed_amendments')
    # ### end Alembic commands ###