"""Update MeasureSponsor model for Phase 3

Revision ID: 26670c52c436
Revises: 01e4e7c97aed
Create Date: 2025-09-08 17:19:56.554829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26670c52c436'
down_revision: Union[str, None] = '01e4e7c97aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measure_sponsors', sa.Column('session_id', sa.UUID(), nullable=False))
    op.add_column('measure_sponsors', sa.Column('legislator_id', sa.UUID(), nullable=True))
    op.add_column('measure_sponsors', sa.Column('measure_sponsor_id', sa.Integer(), nullable=False))
    op.add_column('measure_sponsors', sa.Column('session_key', sa.String(length=20), nullable=False))
    op.add_column('measure_sponsors', sa.Column('measure_prefix', sa.String(length=10), nullable=False))
    op.add_column('measure_sponsors', sa.Column('measure_number', sa.Integer(), nullable=False))
    op.add_column('measure_sponsors', sa.Column('legislator_code', sa.String(length=100), nullable=True))
    op.add_column('measure_sponsors', sa.Column('olis_created_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('measure_sponsors', sa.Column('olis_modified_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('measure_sponsors', sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('measure_sponsors', 'sponsor_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index('idx_sponsor_legislator', 'measure_sponsors', ['legislator_code'], unique=False)
    op.create_index('idx_sponsor_measure', 'measure_sponsors', ['measure_prefix', 'measure_number'], unique=False)
    op.create_index('idx_sponsor_session', 'measure_sponsors', ['session_key'], unique=False)
    op.create_index('idx_sponsor_type', 'measure_sponsors', ['sponsor_type'], unique=False)
    op.create_unique_constraint(None, 'measure_sponsors', ['measure_sponsor_id'])
    op.create_foreign_key(None, 'measure_sponsors', 'legislative_sessions', ['session_id'], ['id'])
    op.create_foreign_key(None, 'measure_sponsors', 'legislators', ['legislator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'measure_sponsors', type_='foreignkey')
    op.drop_constraint(None, 'measure_sponsors', type_='foreignkey')
    op.drop_constraint(None, 'measure_sponsors', type_='unique')
    op.drop_index('idx_sponsor_type', table_name='measure_sponsors')
    op.drop_index('idx_sponsor_session', table_name='measure_sponsors')
    op.drop_index('idx_sponsor_measure', table_name='measure_sponsors')
    op.drop_index('idx_sponsor_legislator', table_name='measure_sponsors')
    op.alter_column('measure_sponsors', 'sponsor_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('measure_sponsors', 'last_synced_at')
    op.drop_column('measure_sponsors', 'olis_modified_date')
    op.drop_column('measure_sponsors', 'olis_created_date')
    op.drop_column('measure_sponsors', 'legislator_code')
    op.drop_column('measure_sponsors', 'measure_number')
    op.drop_column('measure_sponsors', 'measure_prefix')
    op.drop_column('measure_sponsors', 'session_key')
    op.drop_column('measure_sponsors', 'measure_sponsor_id')
    op.drop_column('measure_sponsors', 'legislator_id')
    op.drop_column('measure_sponsors', 'session_id')
    # ### end Alembic commands ###